import { ProgramTab } from '../types';

const RAW_PROGRAM_TABS: ProgramTab[] = [
  // =========================================================================
  // 1. B.Ed 3rd Sem (School Internship & Pedagogy of English)
  // =========================================================================
  {
    id: 'tab-bed',
    type: 'bed',
    title: 'B.Ed',
    subtitle: '3rd Sem · School Internship & Pedagogy of English',
    badge: '3rd Sem',
    color: 'emerald',
    createdAt: '2026-09-27T00:00:00.000Z',
    siTasks: [
      {
        id: 'si-1',
        title: 'Lesson Plan',
        targetCount: 50,
        currentCount: 0,
        status: 'pending',
        notes: 'Target 50 detailed lesson plans across assigned classes',
      },
      {
        id: 'si-2',
        title: 'Reflective Journal',
        targetCount: 20,
        currentCount: 0,
        status: 'pending',
        notes: '20 reflective journal entries documenting classroom experiences and pedagogy learnings',
      },
      {
        id: 'si-3',
        title: 'Peer Observation',
        targetCount: 20,
        currentCount: 0,
        status: 'pending',
        notes: '20 peer teacher observation sheets with constructive feedback',
      },
      {
        id: 'si-4',
        title: 'Action Research',
        targetCount: 1,
        currentCount: 0,
        status: 'pending',
        notes: 'Action research project & diagnostic report on classroom learning barriers',
      },
      {
        id: 'si-5',
        title: 'Diagnostic Report',
        targetCount: 1,
        currentCount: 0,
        status: 'pending',
        notes: 'Comprehensive diagnostic assessment report on identified students',
      },
      {
        id: 'si-6',
        title: 'Co-Curricular Activities',
        targetCount: 4,
        currentCount: 0,
        status: 'pending',
        notes: 'Conduct & record 4 interactive co-curricular school activities',
      },
      {
        id: 'si-7',
        title: 'Environment Activities',
        targetCount: 1,
        currentCount: 0,
        status: 'pending',
        notes: '1 environmental awareness project / school clean-green initiative',
      },
      {
        id: 'si-8',
        title: 'Academic Activities',
        targetCount: 1,
        currentCount: 0,
        status: 'pending',
        notes: '1 academic exhibition / subject quiz / science or history display',
      },
      {
        id: 'si-9',
        title: 'School Record Report',
        targetCount: 1,
        currentCount: 0,
        status: 'pending',
        notes: '1 comprehensive analytical report on school records & administration files',
      },
    ],
    subjects: [
      {
        id: 'bed-sub-english',
        code: 'EDU110',
        name: 'Teaching of English-I (Pedagogy of English)',
        description: 'Nature, aims & objectives, methods, instructional materials and evaluation in English pedagogy',
        chapters: [
          {
            id: 'bed-eng-mod1',
            chapterNumber: 1,
            title: 'Module I: Nature of English Language',
            notes: 'Concept of Language competence, Language Proficiency (BICS & CALPS), Principles of Language Teaching, Status of English in India, Indian English Literature (Evolutionary Perspective), Bilingualism & Multiculturalism impact on ELT in India.',
            readingNotes: false,
            deepStudy: false,
            revision: false,
            isFinished: false,
          },
          {
            id: 'bed-eng-mod2',
            chapterNumber: 2,
            title: 'Module II: Objectives & Instructional Planning in English',
            notes: 'Aims & objectives of Teaching English at schooling stages, Formulation in specific Behavioural Terms, Instructional Planning, Pedagogical analysis of content unit, Unit & Lesson Planning principles, Reflective diary & teaching portfolio.',
            readingNotes: false,
            deepStudy: false,
            revision: false,
            isFinished: false,
          },
          {
            id: 'bed-eng-mod3',
            chapterNumber: 3,
            title: 'Module III: Approaches & Methods of Teaching English',
            notes: 'Approach vs Method, Task-based approach, Cooperative learning, Language Across Curriculum (LAC), Communicative Language Teaching (CLT), Multiple Intelligences, Interactive classroom, Pedagogy of Prose, Poetry, Drama, Grammar & Vocabulary, 4 Basic Skills (LSRW), Study skills.',
            readingNotes: false,
            deepStudy: false,
            revision: false,
            isFinished: false,
          },
          {
            id: 'bed-eng-mod4',
            chapterNumber: 4,
            title: 'Module IV: Instructional Materials & Educational Media',
            notes: 'Effective instructional aids: Smart boards, Chalk Board, Flannel Board, Picture cut-outs, Charts, Audio records, Radio, TV, Films/Filmstrips, OHP, Language Laboratory, Language games, Reading cards, Worksheets, Handouts & PowerPoint presentations, Material design.',
            readingNotes: false,
            deepStudy: false,
            revision: false,
            isFinished: false,
          },
          {
            id: 'bed-eng-mod5',
            chapterNumber: 5,
            title: 'Module V: Evaluation & Learner Assessment in English',
            notes: 'CCE concept and techniques, Testing language skills (LSRW) & language elements (vocabulary, grammar, phonology), Test items development (objective, short answer, essay type) with validity, reliability & usability, Action research (reflective practitioner), Critiquing syllabus & materials, Book reviews, Teaching portfolio.',
            readingNotes: false,
            deepStudy: false,
            revision: false,
            isFinished: false,
          },
        ],
      },
      {
        id: 'bed-sub-wtec',
        code: 'WTEC',
        name: 'Work and Technology Education in Curriculum',
        description: 'Vocational & technological integration in modern curriculum',
        chapters: [
          { id: 'bed-w-1', chapterNumber: 1, title: 'Concept & Philosophy of Work Education', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'bed-w-2', chapterNumber: 2, title: 'Integrating Technology with Classroom Pedagogy', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'bed-w-3', chapterNumber: 3, title: 'Project-Based Work Learning Models', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'bed-w-4', chapterNumber: 4, title: 'Evaluation Rubrics for Work Education Projects', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'bed-sub-epc',
        code: 'EPC',
        name: 'Enhancing Professional Capacities (EPC)',
        description: 'ICT in Education & Drama/Art in Education',
        chapters: [
          { id: 'bed-e-1', chapterNumber: 1, title: 'Critical Understanding of ICT Tools in School', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'bed-e-2', chapterNumber: 2, title: 'Drama, Art & Theater as Experiential Learning', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'bed-e-3', chapterNumber: 3, title: 'Self-Understanding & Teacher Personality Development', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
    ],
  },

  // =========================================================================
  // 2. M.A. History 2nd Year (IGNOU MAHI - 6 Selected Subjects, 173 Units)
  // =========================================================================
  {
    id: 'tab-ma',
    type: 'ma',
    title: 'M.A.',
    subtitle: 'History 2nd Year · IGNOU MAHI (6 Selected Subjects)',
    badge: 'IGNOU',
    color: 'blue',
    createdAt: '2026-09-27T00:00:00.000Z',
    subjects: [
      // 1. MHI-103: Historiography and Research Methods (32 Units)
      {
        id: 'ma-mhi103',
        code: 'MHI-103',
        name: 'Historiography and Research Methods',
        description: 'Non-Indian & Indian historiography paradigms, historical evidence, interpretation and writing methods (32 Units)',
        chapters: [
          // Part I: Non-Indian Historiography
          { id: 'mhi103-u1', chapterNumber: 1, title: 'Unit 1: Greek and Roman Traditions', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u2', chapterNumber: 2, title: 'Unit 2: Traditional Chinese Historiography', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u3', chapterNumber: 3, title: 'Unit 3: Western Medieval Historiography', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u4', chapterNumber: 4, title: 'Unit 4: Arabic and Persian Historiography in Medieval Period', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u5', chapterNumber: 5, title: 'Unit 5: Mainstream Western Historiography in the Nineteenth Century', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u6', chapterNumber: 6, title: 'Unit 6: Classical Marxist Thinking on History', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u7', chapterNumber: 7, title: 'Unit 7: Western Marxist Historiography', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u8', chapterNumber: 8, title: 'Unit 8: The Annales School', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u9', chapterNumber: 9, title: 'Unit 9: Local, Oral and Micro Histories', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u10', chapterNumber: 10, title: 'Unit 10: Postmodernism and History-Writing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u11', chapterNumber: 11, title: 'Unit 11: Environmental History', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Part II: Indian Historiography
          { id: 'mhi103-u12', chapterNumber: 12, title: 'Unit 12: Historiographical Traditions in Early India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u13', chapterNumber: 13, title: 'Unit 13: Indo-Persian Historiography in Medieval India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u14', chapterNumber: 14, title: 'Unit 14: Colonial Historiography in India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u15', chapterNumber: 15, title: 'Unit 15: Nationalist Historiography in India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u16', chapterNumber: 16, title: 'Unit 16: Communalist Trends', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u17', chapterNumber: 17, title: 'Unit 17: Indian Marxist History-Writing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u18', chapterNumber: 18, title: 'Unit 18: The Cambridge School', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u19', chapterNumber: 19, title: 'Unit 19: History from Below', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u20', chapterNumber: 20, title: 'Unit 20: Subaltern Studies', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u21', chapterNumber: 21, title: 'Unit 21: Gender in Indian History-Writing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u22', chapterNumber: 22, title: 'Unit 22: The Idea of Race in Indian History-Writing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u23', chapterNumber: 23, title: 'Unit 23: Peasantry, Working Class, Caste and Tribe', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u24', chapterNumber: 24, title: 'Unit 24: Religion and Culture', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u25', chapterNumber: 25, title: 'Unit 25: Environment, Science and Technology', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u26', chapterNumber: 26, title: 'Unit 26: Economic History in India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Part III: Research and Writing Method
          { id: 'mhi103-u27', chapterNumber: 27, title: 'Unit 27: Historical Sources', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u28', chapterNumber: 28, title: 'Unit 28: Analysis and Organization of Evidences', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u29', chapterNumber: 29, title: 'Unit 29: Generalisation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u30', chapterNumber: 30, title: 'Unit 30: Causation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u31', chapterNumber: 31, title: 'Unit 31: Objectivity and Interpretation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi103-u32', chapterNumber: 32, title: 'Unit 32: Ethics in History-Writing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },

      // 2. MHI-109: Indian National Movement (36 Units)
      {
        id: 'ma-mhi109',
        code: 'MHI-109',
        name: 'Indian National Movement',
        description: 'Nationalism, anti-colonial struggles, mass movements, social groups, constitution making & legacies (36 Units)',
        chapters: [
          { id: 'mhi109-u1', chapterNumber: 1, title: 'Unit 1: Nation and Nationalism', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u2', chapterNumber: 2, title: 'Unit 2: Anti-colonial National Liberation Movement: Asia and Africa', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u3', chapterNumber: 3, title: 'Unit 3: Perspectives on Indian Nationalism-I', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u4', chapterNumber: 4, title: 'Unit 4: Perspectives on Indian Nationalism-II', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u5', chapterNumber: 5, title: 'Unit 5: Revolt of 1857', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u6', chapterNumber: 6, title: 'Unit 6: Foundations of Indian Nationalism', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u7', chapterNumber: 7, title: 'Unit 7: Economic Nationalism', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u8', chapterNumber: 8, title: 'Unit 8: Resistance to Colonialism in Intellectual and Social Spheres', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u9', chapterNumber: 9, title: 'Unit 9: Towards Radical and Mass Politics - Swadeshi Movement', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u10', chapterNumber: 10, title: 'Unit 10: Nationalist Politics during the First World War and the Turning Point', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u11', chapterNumber: 11, title: 'Unit 11: Emergence of Gandhi', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u12', chapterNumber: 12, title: 'Unit 12: Khilafat and Non-Cooperation Movements', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u13', chapterNumber: 13, title: 'Unit 13: Revolutionary Trends', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u14', chapterNumber: 14, title: 'Unit 14: Resistance within the Councils and Outside', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u15', chapterNumber: 15, title: 'Unit 15: Civil Disobedience Movement', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u16', chapterNumber: 16, title: 'Unit 16: Constitutional Developments', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u17', chapterNumber: 17, title: 'Unit 17: The Ideological Spectrum in the 1930s', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u18', chapterNumber: 18, title: 'Unit 18: Nationalist Struggles in the Princely States', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u19', chapterNumber: 19, title: 'Unit 19: Congress Ministries', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u20', chapterNumber: 20, title: 'Unit 20: Prelude to Quit India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u21', chapterNumber: 21, title: 'Unit 21: Quit India Movement', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u22', chapterNumber: 22, title: 'Unit 22: Subhas Chandra Bose and Azad Hind Fauj', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u23', chapterNumber: 23, title: 'Unit 23: Post-War National Upsurge, 1945-47', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u24', chapterNumber: 24, title: 'Unit 24: Towards Freedom-I', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u25', chapterNumber: 25, title: 'Unit 25: Towards Freedom-II', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u26', chapterNumber: 26, title: 'Unit 26: National Movement and the Peasantry', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u27', chapterNumber: 27, title: 'Unit 27: National Movement and the Working Class', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u28', chapterNumber: 28, title: 'Unit 28: National Movement and the Capitalist Class', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u29', chapterNumber: 29, title: 'Unit 29: National Movement and the Landlords', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u30', chapterNumber: 30, title: 'Unit 30: National Movement and Women', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u31', chapterNumber: 31, title: 'Unit 31: National Movement and the Dalits', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u32', chapterNumber: 32, title: 'Unit 32: National Movement and the Minorities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u33', chapterNumber: 33, title: 'Unit 33: National Movement and its Strategies', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u34', chapterNumber: 34, title: 'Unit 34: Nationalist Movement and the Communal Problem', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u35', chapterNumber: 35, title: 'Unit 35: Making of the Indian Constitution', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi109-u36', chapterNumber: 36, title: 'Unit 36: Legacies of the National Movement', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },

      // 3. MPSE-004: Social and Political Thought in Modern India (15 Units)
      {
        id: 'ma-mpse004',
        code: 'MPSE-004',
        name: 'Social and Political Thought in Modern India',
        description: 'Intellectual history, colonial modernity, Gandhi, Ambedkar, Nehru, Tagore, socialist & communist thinkers (15 Units)',
        chapters: [
          { id: 'mpse-u1', chapterNumber: 1, title: 'Unit 1: Pre-Modern Socio-Religious and Political Thought in India: Diverse Strands', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u2', chapterNumber: 2, title: 'Unit 2: Orientalist Discourse and Colonial Modernity', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u3', chapterNumber: 3, title: 'Unit 3: Salient Features of Modern Indian Political Thought', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u4', chapterNumber: 4, title: 'Unit 4: Early Nationalist Responses: Rammohan Roy, Bankim Chandra Chatterjee, Dayanand Saraswati and Jyotiba Phule', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u5', chapterNumber: 5, title: 'Unit 5: Moderates and Extremists: Dadabhai Naoroji, M.G. Ranade and B.G. Tilak', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u6', chapterNumber: 6, title: 'Unit 6: Hinduism: Swami Vivekananda and Sri Aurobindo Ghosh', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u7', chapterNumber: 7, title: 'Unit 7: Hindutva: V.D. Savarkar and M.S. Golwalkar', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u8', chapterNumber: 8, title: 'Unit 8: Muslim Thought: Sir Syed Ahmed Khan, Mohammed Iqbal, Maulana Maudoodi and Mohammed Ali Jinnah', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u9', chapterNumber: 9, title: 'Unit 9: Nation and Identity Concerns: E.V. Ramaswamy Naicker, Nazrul Islam, Pandita Ramabai, Jaipal Singh and Kahn Singh', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u10', chapterNumber: 10, title: 'Unit 10: M.K. Gandhi', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u11', chapterNumber: 11, title: 'Unit 11: Jawaharlal Nehru', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u12', chapterNumber: 12, title: 'Unit 12: B.R. Ambedkar', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u13', chapterNumber: 13, title: 'Unit 13: Rabindranath Tagore', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u14', chapterNumber: 14, title: 'Unit 14: Communist Thought: M.N. Roy and E.M.S. Namboodiripad', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mpse-u15', chapterNumber: 15, title: 'Unit 15: Socialist Thought: Rammanohar Lohia and Jayaprakash Narayan', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },

      // 4. MHI-108: Environmental Histories of the Indian Subcontinent (36 Units)
      {
        id: 'ma-mhi108',
        code: 'MHI-108',
        name: 'Environmental Histories of the Indian Subcontinent',
        description: 'Paleo-environments, monsoon ecologies, colonial resource regimes, waterscapes, cities & Anthropocene (36 Units)',
        chapters: [
          // Block 1: Writing Environmental History
          { id: 'mhi108-u1', chapterNumber: 1, title: 'Unit 1: Inter-Disciplinary Approaches', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u2', chapterNumber: 2, title: 'Unit 2: Nature and Women', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u3', chapterNumber: 3, title: 'Unit 3: Variety of Sources: Archival', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u4', chapterNumber: 4, title: 'Unit 4: Variety of Sources: Archaeological', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u5', chapterNumber: 5, title: 'Unit 5: Variety of Sources: Material Culture', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u6', chapterNumber: 6, title: 'Unit 6: Varied Knowledge Systems', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 2: Paleo-environments
          { id: 'mhi108-u7', chapterNumber: 7, title: 'Unit 7: Paleo-Environments and Adaptations', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 3: Monsoon Ecologies
          { id: 'mhi108-u8', chapterNumber: 8, title: 'Unit 8: Riparian, Deltaic and Doab', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u9', chapterNumber: 9, title: 'Unit 9: Forests and Foragers; Sacred Groves', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 4: Agro-Pastoral Regimes
          { id: 'mhi108-u10', chapterNumber: 10, title: 'Unit 10: Arid and Semi-Arid Landscapes: Grasslands, Deserts', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u11', chapterNumber: 11, title: 'Unit 11: Hills and Mountains', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u12', chapterNumber: 12, title: 'Unit 12: Deltaic Regions and Coastal Terrains', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u13', chapterNumber: 13, title: 'Unit 13: Animal Energy and Animals as Symbols of Power', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u14', chapterNumber: 14, title: 'Unit 14: Shikar and Gunpowder', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 5: Agrarian Regimes Under Colonial Rule
          { id: 'mhi108-u15', chapterNumber: 15, title: 'Unit 15: Changing Land Use', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u16', chapterNumber: 16, title: 'Unit 16: Deforestation, Reforestation and Afforestation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 6: Global Connections
          { id: 'mhi108-u17', chapterNumber: 17, title: 'Unit 17: Nature, Capital and Imperialism-I', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u18', chapterNumber: 18, title: 'Unit 18: Nature, Capital and Imperialism-II', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u19', chapterNumber: 19, title: 'Unit 19: Industrial Agriculture', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 7: Control and Conservation of Nature
          { id: 'mhi108-u20', chapterNumber: 20, title: 'Unit 20: Loss of Livelihood and Migrations', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u21', chapterNumber: 21, title: 'Unit 21: Forest Conservation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u22', chapterNumber: 22, title: 'Unit 22: National Parks and Zoological Parks', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u23', chapterNumber: 23, title: 'Unit 23: Mining', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 8: Waterscapes
          { id: 'mhi108-u24', chapterNumber: 24, title: 'Unit 24: Irrigation: Canal Colonies', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u25', chapterNumber: 25, title: 'Unit 25: Wetlands', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u26', chapterNumber: 26, title: 'Unit 26: Big Dams and Displacements', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u27', chapterNumber: 27, title: 'Unit 27: Fisheries', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 9: Urban Spaces
          { id: 'mhi108-u28', chapterNumber: 28, title: 'Unit 28: Vijayanagara', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u29', chapterNumber: 29, title: 'Unit 29: Cities of Delhi', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u30', chapterNumber: 30, title: 'Unit 30: Kolkata and Brihan-Mumbai', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u31', chapterNumber: 31, title: 'Unit 31: Jodhpur and Jaisalmer', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Block 10: Provincialising the Anthropocene
          { id: 'mhi108-u32', chapterNumber: 32, title: 'Unit 32: New Energy Regimes', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u33', chapterNumber: 33, title: 'Unit 33: Growing Human-Wildlife Conflicts', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u34', chapterNumber: 34, title: 'Unit 34: Natural Calamities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u35', chapterNumber: 35, title: 'Unit 35: Industrial Pollution and Disasters', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi108-u36', chapterNumber: 36, title: 'Unit 36: Climate Change', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },

      // 5. MHI-110: Urbanisation in India-1: From the Earliest Times to c. 1300 (25 Units)
      {
        id: 'ma-mhi110',
        code: 'MHI-110',
        name: 'Urbanisation in India-1: Earliest Times to c. 1300',
        description: 'Harappan urbanism, early historic north/south cities, and early medieval urban patterns (25 Units)',
        chapters: [
          // Theme 1: Introduction to Urban History
          { id: 'mhi110-u1', chapterNumber: 1, title: 'Unit 1: Understanding Urban History', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u2', chapterNumber: 2, title: 'Unit 2: Approaches to the Study of Ancient Cities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 2: The Earliest Cities in the Subcontinent
          { id: 'mhi110-u3', chapterNumber: 3, title: 'Unit 3: An Introduction to Early Urbanism', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u4', chapterNumber: 4, title: 'Unit 4: Distribution and Morphology of Harappan Settlements', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u5', chapterNumber: 5, title: 'Unit 5: Harappan Economy and Occupations', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u6', chapterNumber: 6, title: 'Unit 6: Harappan Urban Societies', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u7', chapterNumber: 7, title: 'Unit 7: Case Study of a Major Urban Centre: Mohenjodaro', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 3: Early Historic Cities - North India
          { id: 'mhi110-u8', chapterNumber: 8, title: 'Unit 8: Archaeology of Early Historic Urban Centres in North India: Emergence and Characteristics', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u9', chapterNumber: 9, title: 'Unit 9: Urban Centres and Other Types of Spaces', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u10', chapterNumber: 10, title: 'Unit 10: Cities in Texts', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u11', chapterNumber: 11, title: 'Unit 11: Early Historic Cities in the Taxila Valley: Archaeological Perspectives', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u12', chapterNumber: 12, title: 'Unit 12: Case Study: Pataliputra', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u13', chapterNumber: 13, title: 'Unit 13: Case Study: Mathura', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 4: Early Historic Cities - Deccan and South India
          { id: 'mhi110-u14', chapterNumber: 14, title: 'Unit 14: Archaeology of the Emergence of Early Cities and Characteristics: South India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u15', chapterNumber: 15, title: 'Unit 15: Case Study: Nagarjunakonda', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u16', chapterNumber: 16, title: 'Unit 16: Case Study: Amaravati', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u17', chapterNumber: 17, title: 'Unit 17: Case Study: Kanchipuram and Tondaimandalam', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u18', chapterNumber: 18, title: 'Unit 18: Case Study: Kaveripattanam/Puhar', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 5: Patterns of Early Medieval Urbanisation
          { id: 'mhi110-u19', chapterNumber: 19, title: 'Unit 19: Urbanisation in Post-Gupta Period: Archaeological Evidence', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u20', chapterNumber: 20, title: 'Unit 20: Early Medieval Urbanisation from Epigraphy and Texts', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u21', chapterNumber: 21, title: 'Unit 21: Case Study: Kannauj', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u22', chapterNumber: 22, title: 'Unit 22: Case Study: Pratishthan', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u23', chapterNumber: 23, title: 'Unit 23: Port Town: Chandraketugarh', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u24', chapterNumber: 24, title: 'Unit 24: Case Study: Sisupalgarh', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi110-u25', chapterNumber: 25, title: 'Unit 25: Case Study: Al-Mansura/Brahmanabad', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },

      // 6. MHI-111: Urbanisation in India-2: c. 1300-1950 (29 Units)
      {
        id: 'ma-mhi111',
        code: 'MHI-111',
        name: 'Urbanisation in India-2: c. 1300-1950',
        description: 'Sultanate cities, Mughal urban centers, colonial port cities, city planning & post-colonial urbanism (29 Units)',
        chapters: [
          // Theme 1: Introduction to Urban History
          { id: 'mhi111-u1', chapterNumber: 1, title: 'Unit 1: Approaches to the Study of Medieval Urbanisation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u2', chapterNumber: 2, title: 'Unit 2: Themes on Modern Cities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 2: Patterns of Urbanisation, c. 1300-1600
          { id: 'mhi111-u3', chapterNumber: 3, title: 'Unit 3: Sultanate and Its Cities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u4', chapterNumber: 4, title: 'Unit 4: Regional Cities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u5', chapterNumber: 5, title: 'Unit 5: Temple Towns in Peninsular India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u6', chapterNumber: 6, title: 'Unit 6: Southern Dimension: The Glory of Vijayanagara', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u7', chapterNumber: 7, title: 'Unit 7: Sultanate Capital Cities in the Delhi Riverine Plain', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u8', chapterNumber: 8, title: 'Unit 8: Port Town: Cambay', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 3: Patterns of Urbanisation in Mughal India
          { id: 'mhi111-u9', chapterNumber: 9, title: 'Unit 9: Spatial Characteristics of Mughal Cities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u10', chapterNumber: 10, title: 'Unit 10: Urban Patterns in Medieval Deccan', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u11', chapterNumber: 11, title: 'Unit 11: Urban Culture and Society', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u12', chapterNumber: 12, title: 'Unit 12: Primate Cities: Agra-Fatehpur Sikri-Shahjahanabad', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u13', chapterNumber: 13, title: 'Unit 13: Sacred City Spaces: Ajmer-Banaras-Pandharpur', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u14', chapterNumber: 14, title: 'Unit 14: Case Study: Masulipatnam', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u15', chapterNumber: 15, title: 'Unit 15: Case Study: Surat', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 4: Early Modern Cities
          { id: 'mhi111-u16', chapterNumber: 16, title: 'Unit 16: Capitalism, Colonialism and Cities in Early Modern India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u17', chapterNumber: 17, title: 'Unit 17: Port Cities: 16th to 18th Centuries', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u18', chapterNumber: 18, title: 'Unit 18: Cities in the 18th Century-I', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u19', chapterNumber: 19, title: 'Unit 19: Cities in the 18th Century-II', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u20', chapterNumber: 20, title: 'Unit 20: Case Study: Lucknow', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u21', chapterNumber: 21, title: 'Unit 21: Case Study: Pondicherry', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 5: Colonial Cities-I
          { id: 'mhi111-u22', chapterNumber: 22, title: 'Unit 22: Dependent Urbanisation and New Urban Forms in Colonial India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u23', chapterNumber: 23, title: 'Unit 23: Race, Class and Ethnicity in the Colonial City', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u24', chapterNumber: 24, title: 'Unit 24: The City as the Site of Spectacles: Colonial Delhi and the New Imperial Capital', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u25', chapterNumber: 25, title: 'Unit 25: The City as the Site of Movements', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 6: Colonial Cities-II
          { id: 'mhi111-u26', chapterNumber: 26, title: 'Unit 26: Modernity and the City in Colonial India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u27', chapterNumber: 27, title: 'Unit 27: City Planning in India under British Rule', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'mhi111-u28', chapterNumber: 28, title: 'Unit 28: Case Study: Bombay', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          // Theme 7: Post-Colonial Cities
          { id: 'mhi111-u29', chapterNumber: 29, title: 'Unit 29: Predicaments of Post-Colonial Cities', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
    ],
  },

  // =========================================================================
  // 3. CTET (Central Teacher Eligibility Test - Paper 1 & Paper 2)
  // =========================================================================
  {
    id: 'tab-ctet',
    type: 'ctet',
    title: 'CTET',
    subtitle: 'Paper II & I · Child Development, Social Science, English & Hindi',
    badge: 'Paper II & I',
    color: 'amber',
    createdAt: '2026-09-27T00:00:00.000Z',
    subjects: [
      {
        id: 'ctet-sub-cdp',
        code: 'CDP',
        name: 'Child Development & Pedagogy',
        description: 'Development concepts, Piaget, Vygotsky, Kohlberg, inclusive education & learning psychology (Paper 1 & 2)',
        chapters: [
          { id: 'ctet-cdp-1', chapterNumber: 1, title: 'Concept of Development and its Relationship with Learning', notes: 'Principles of development, influence of heredity and environment, stages of growth', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-cdp-2', chapterNumber: 2, title: 'Theories of Piaget, Kohlberg and Vygotsky: Constructs & Perspectives', notes: 'Stages of cognitive development, moral dilemmas, zone of proximal development (ZPD) and scaffolding', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-cdp-3', chapterNumber: 3, title: 'Concepts of Child-Centered and Progressive Education', notes: 'John Dewey philosophy, democratic classroom, learning by doing, active participation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-cdp-4', chapterNumber: 4, title: 'Construct of Intelligence, Multi-Dimensional Intelligence & Language & Thought', notes: 'Gardner multiple intelligences, Sternberg triarchic theory, language as cognitive tool', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-cdp-5', chapterNumber: 5, title: 'Addressing Learners from Diverse Backgrounds & Inclusive Education', notes: 'Children with special needs (CWSN), learning disabilities (dyslexia, dyscalculia), gifted learners', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-cdp-6', chapterNumber: 6, title: 'How Children Think and Learn, Motivation and Classroom Learning Processes', notes: 'Intrinsic vs extrinsic motivation, memory processes, problem solving & constructivist pedagogy', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'ctet-sub-sst',
        code: 'SST',
        name: 'Social Studies / Social Science (Paper II)',
        description: 'History, Geography, Social & Political Life (Class 6-8 NCERT) & Pedagogical Issues (60 Marks)',
        chapters: [
          { id: 'ctet-ss-1', chapterNumber: 1, title: 'History: Earliest Societies, First Cities (Harappa), Vedic Period & Early Empires', notes: 'When, Where and How, First Farmers, First Cities, Mauryan Empire, Ashoka, Post-Mauryan trade', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-2', chapterNumber: 2, title: 'History: Medieval Period, Delhi Sultans, Mughals, Regional Cultures & Architecture', notes: 'New Kings, Delhi Sultanate administration, Mughal court, Bhakti-Sufi traditions', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-3', chapterNumber: 3, title: 'History: Colonial Rule, 1857 Revolt, Social Reform Movements & Freedom Struggle', notes: 'East India Company expansion, rural economy, 1857 uprising, women reformers, caste challenges & nationalism', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-4', chapterNumber: 4, title: 'Geography: Earth in Solar System, Globe, Latitudes, Longitudes, Motions & Maps', notes: 'Rotation, revolution, time zones, map scales, physical features of India', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-5', chapterNumber: 5, title: 'Geography: Environment, Lithosphere, Atmosphere, Hydrosphere, Resources & Agriculture', notes: 'Ecosystem, air composition, water cycle, renewable resources, major cropping patterns', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-6', chapterNumber: 6, title: 'Social & Political Life: Diversity, Government, Local Govt (Panchayati Raj & Municipalities)', notes: 'Understanding diversity, prejudice, levels of government, rural & urban administration', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-7', chapterNumber: 7, title: 'Social & Political Life: Constitution, Democracy, Parliament, Judiciary & Social Justice', notes: 'Preamble, fundamental rights, legislative process, judicial review, marginalized groups', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-8', chapterNumber: 8, title: 'Pedagogy of Social Science: Concept, Classroom Processes, Inquiries & Empirical Evidence', notes: 'Developing critical thinking, project method, problem solving in SST classrooms', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-ss-9', chapterNumber: 9, title: 'SST Resources & Evaluation: Primary vs Secondary Sources, CCE & Remedial Teaching', notes: 'Archaeological & documentary sources, diagnostic assessments, museum & field visits', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'ctet-sub-lang1',
        code: 'LANG-1',
        name: 'Language 1: English (Comprehension & Pedagogy)',
        description: 'Unseen passages, grammar in context & language acquisition methodology (30 Marks)',
        chapters: [
          { id: 'ctet-en-1', chapterNumber: 1, title: 'Reading Comprehension: Unseen Prose Passages & Poetry Analysis', notes: 'Inference, vocabulary, lexical items, literary appreciation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-en-2', chapterNumber: 2, title: 'Learning and Acquisition: Language Theories (Chomsky, Krashen, Skinner)', notes: 'LAD, critical period hypothesis, monitor model, natural order hypothesis', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-en-3', chapterNumber: 3, title: 'Principles of Language Teaching & Role of Listening and Speaking (LSRW)', notes: 'Oral approach, communicative competence, phonetic skills, active listening', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-en-4', chapterNumber: 4, title: 'Grammar in Context & Language Mechanics in Classroom', notes: 'Functional grammar, parts of speech in contextual usage, syntax and sentence construction', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-en-5', chapterNumber: 5, title: 'Challenges of Teaching in Diverse Classrooms & Learning Disabilities', notes: 'Multilingual classrooms, speech impediments, dyslexia, remedial strategies', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-en-6', chapterNumber: 6, title: 'Teaching Learning Materials (TLM), Multi-media & CCE Evaluation', notes: 'Textbooks, audio-visual aids, digital resources, continuous language evaluation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'ctet-sub-lang2',
        code: 'LANG-2',
        name: 'Language 2: Hindi (हिंदी भाषा एवं शिक्षण शास्त्र)',
        description: 'अपठित गद्यांश, व्यावहारिक व्याकरण एवं भाषा विकास की शिक्षा विधि (30 Marks)',
        chapters: [
          { id: 'ctet-hi-1', chapterNumber: 1, title: 'अपठित गद्यांश एवं पद्यांश (भावार्थ, व्याकरण व शब्द सामर्थ्य)', notes: 'साहित्यिक व विवरणात्मक गद्यांश, विलोम, पर्यायवाची, मुहावरे व लोकोक्तियाँ', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-hi-2', chapterNumber: 2, title: 'भाषा अर्जन एवं अधिगम (भाषा विकास के सिद्धांत)', notes: 'मातृभाषा शिक्षण, द्वितीय भाषा अधिगम, भाषा के कार्य एवं बालक में भाषा विकास', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-hi-3', chapterNumber: 3, title: 'हिंदी व्यावहारिक व्याकरण: संज्ञा, सर्वनाम, क्रिया, विशेषण, संधि व समास', notes: 'वर्ण विचार, शब्द भेद, संधि (स्वर, व्यंजन), समास, उपसर्ग, प्रत्यय, कारक व काल', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-hi-4', chapterNumber: 4, title: 'भाषायी कौशल: श्रवण, वाचन, पठन एवं लेखन कौशल (LSRW)', notes: 'शुद्ध उच्चारण, सस्वर व मौन पठन, वर्तनीगत अशुद्धियाँ एवं उनका निवारण', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-hi-5', chapterNumber: 5, title: 'कक्षा शिक्षण में विविधता, बहुभाषिकता एवं भाषाई विकार', notes: 'बहुभाषिक कक्षा एक संसाधन के रूप में, भाषा संबंधी कठिनाइयाँ ও त्रुटियाँ', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'ctet-hi-6', chapterNumber: 6, title: 'शिक्षण अधिगम सामग्री (TLM), पाठ्य-पुस्तक एवं उपचारात्मक शिक्षण', notes: 'दृश्य-श्रव्य साधन, भाषा प्रयोगशाला, सतत एवं समग्र मूल्यांकन (CCE), निदानात्मक व उपचारात्मक शिक्षण', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
    ],
  },

  // =========================================================================
  // 4. UGC NET (Paper 1: General & Paper 2: History - Complete 10+10 Units)
  // =========================================================================
  {
    id: 'tab-ugc_net',
    type: 'ugc_net',
    title: 'UGC NET',
    subtitle: 'NTA UGC NET · Paper 1 (General 10 Units) & Paper 2 (History 10 Units)',
    badge: 'JRF / NET',
    color: 'purple',
    createdAt: '2026-09-27T00:00:00.000Z',
    subjects: [
      {
        id: 'net-paper1',
        code: 'PAPER-1',
        name: 'Paper 1: General Paper on Teaching & Research Aptitude',
        description: 'Official 10 NTA Units: Teaching, Research, Logic, ICT, Environment & Higher Education (100 Marks)',
        chapters: [
          { id: 'net-p1-u1', chapterNumber: 1, title: 'Unit 1: Teaching Aptitude (Levels of Teaching, Learner Traits, CBCS & Evaluation Systems)', notes: 'Memory, Understanding & Reflective levels; Teacher vs Learner centered; SWAYAM, SWAYAMPRABHA, MOOCs; Computer-based testing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u2', chapterNumber: 2, title: 'Unit 2: Research Aptitude (Types, Methods, Ethics, Paper/Thesis Writing, ICT in Research)', notes: 'Positivism and Post-positivistic approach; Experimental, Descriptive, Historical, Qualitative & Quantitative; Plagiarism & citation styles', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u3', chapterNumber: 3, title: 'Unit 3: Reading Comprehension Techniques & Question Strategies', notes: 'Critical analytical reasoning on textual passages and thematic deductions', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u4', chapterNumber: 4, title: 'Unit 4: Communication (Classroom Communication, Types, Barriers & Mass-Media and Society)', notes: 'Verbal & Non-verbal, Inter-cultural and group communication; Semantic & psychological barriers', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u5', chapterNumber: 5, title: 'Unit 5: Mathematical Reasoning and Aptitude (Number Series, Letter Codes, Ratios, Speed & Interest)', notes: 'Fraction, Time & Distance, Ratio and Proportion, Percentage, Profit and Loss, Interest and Discounting', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u6', chapterNumber: 6, title: 'Unit 6: Logical Reasoning (Pramanas, Indian Logic, Syllogisms, Venn Diagrams & Fallacies)', notes: 'Structure of categorical propositions, Square of Opposition; Pratyaksha, Anumana, Upamana, Sabda, Arthapatti, Anupalabdhi; Hetvabhasa', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u7', chapterNumber: 7, title: 'Unit 7: Data Interpretation (Quantitative Graphical & Tabular Analysis)', notes: 'Sources, acquisition and classification of data; Tables, Bar-chart, Histograms, Pie-chart and Line-chart; Data and Governance', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u8', chapterNumber: 8, title: 'Unit 8: Information and Communication Technology (ICT Acronyms, Internet & Digital Initiatives)', notes: 'General abbreviations; Internet, Intranet, E-mail, Audio and Video-conferencing; Digital initiatives in higher education (NAD, NDL)', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u9', chapterNumber: 9, title: 'Unit 9: People, Development and Environment (MDGs, SDGs, Pollutants & Climate Treaties)', notes: 'Human and environment interaction; Air, water, soil, noise pollutants; Kyoto Protocol, Paris Agreement, International Solar Alliance (ISA)', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p1-u10', chapterNumber: 10, title: 'Unit 10: Higher Education System (Ancient Institutions, Governance, Policies & NEP 2020)', notes: 'Institutions of higher learning in ancient India (Takshashila, Nalanda); Value education, Environmental education; NEP 2020 structures', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'net-paper2-history',
        code: 'PAPER-2',
        name: 'Paper 2: History (Core Subject - Complete 10 Units)',
        description: 'Official NTA 10 Units: Ancient, Medieval, Modern Indian History & Historiographical Methods (200 Marks)',
        chapters: [
          { id: 'net-p2-u1', chapterNumber: 1, title: 'Unit 1: Negotiating the Sources: Archaeological, Harappan Civilization & Vedic Period', notes: 'Epigraphy, numismatics, radiocarbon dating; Indus urbanism, settlement patterns, trade; Vedic polity, society and literature', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u2', chapterNumber: 2, title: 'Unit 2: From State to Empire: Mahajanapadas, Mauryas, Sungas, Kushanas & Satavahanas', notes: 'Second Urbanization, Magadha rise, Arthashastra, Ashoka edicts & Dhamma; Post-Mauryan trade with Roman world, Indo-Greeks', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u3', chapterNumber: 3, title: 'Unit 3: Emergence of Regional Kingdoms: Gupta, Vakataka, Harsha & Early Medieval Feudalism', notes: 'Gupta administration, land grants, agrarian economy; Debate on Indian Feudalism; Pallavas, Chalukyas, Cholas & maritime trade', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u4', chapterNumber: 4, title: 'Unit 4: Sources of Medieval Indian History & Delhi Sultanate Polity', notes: 'Persian chroniclers (Barani, Isami, Ibn Battuta); Delhi Sultanate establishment, Balban, Alauddin Khalji reforms, Iqta system', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u5', chapterNumber: 5, title: 'Unit 5: Administration & Economy: Mughal Empire, Vijayanagara, Bahmani & Marathas', notes: 'Akbar administrative innovations, Mansabdari & Jagirdari; Vijayanagara Nayankara system; Shivaji administration, Chauth & Sardeshmukhi', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u6', chapterNumber: 6, title: 'Unit 6: Society and Culture: Bhakti and Sufi Movements, Sikhism & Art and Architecture', notes: 'Sufi Silsilas, Bhakti saints (Kabir, Nanak, Mirabai); Mughal painting & architecture; Indo-Islamic urban centers & commerce', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u7', chapterNumber: 7, title: 'Unit 7: Sources of Modern Indian History, British Paramountcy & 1857 Resistance', notes: 'Archival records, private papers; Anglo-Maratha, Anglo-Mysore, Anglo-Sikh wars; Subsidiary Alliance & Doctrine of Lapse; 1857 Uprising', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u8', chapterNumber: 8, title: 'Unit 8: Colonial Economy: Land Revenue, Commercialization, Railways & Drain of Wealth', notes: 'Permanent Settlement, Ryotwari, Mahalwari; De-industrialization, handicrafts decline, Famines & Dadabhai Naoroji drain theory', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u9', chapterNumber: 9, title: 'Unit 9: Rise of Indian Nationalism: INC, Swadeshi, Gandhian Movements, Left Politics & Partition', notes: 'Moderates, Extremists, Home Rule; Non-Cooperation, Civil Disobedience, Quit India; INA, Subhas Chandra Bose, communalism & 1947', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'net-p2-u10', chapterNumber: 10, title: 'Unit 10: Historical Method, Research Methodology, Historiography & Primary Analysis', notes: 'Primary vs secondary data; Causation, generalisation, objectivity; Colonial, Nationalist, Marxist, Cambridge and Subaltern historiography', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
    ],
  },

  // =========================================================================
  // 5. Canva Course (Tutedude Certified Graphic Design & Visual Suite)
  // =========================================================================
  {
    id: 'tab-canva',
    type: 'canva',
    title: 'Canva',
    subtitle: 'Tutedude Certified Course · Graphic Design, Visual Suite & AI',
    badge: 'Tutedude',
    color: 'cyan',
    createdAt: '2026-09-27T00:00:00.000Z',
    subjects: [
      {
        id: 'canva-mod-1',
        code: 'MOD-1',
        name: 'Workspace Essentials & Navigation',
        description: 'Dashboard, canvas setup, shortcuts, mobile vs desktop & cloud organization',
        chapters: [
          { id: 'canva-1-1', chapterNumber: 1, title: 'Canva Interface Tour, Home Dashboard & Navigation Essentials', notes: 'Workspace tour, custom dimensions, file naming & folder organization', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-1-2', chapterNumber: 2, title: 'Canvas Controls: Rulers, Guides, Margins & Print Bleed Setup', notes: 'Precision alignments, snap-to-grid, margins and bleed boundaries', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-1-3', chapterNumber: 3, title: 'Time-saving Keyboard Shortcuts & Quick Commands in Canva', notes: 'Grouping, layering, duplicating, lock elements, zoom & pan shortcuts', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-1-4', chapterNumber: 4, title: 'Canva Mobile App vs Desktop Workflow & Cloud Syncing', notes: 'Designing on mobile, asset syncing, offline saving & multi-device handoff', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-2',
        code: 'MOD-2',
        name: 'Design Principles & Visual Hierarchy',
        description: 'Layout composition, visual balance, color theory & typography pairing',
        chapters: [
          { id: 'canva-2-1', chapterNumber: 1, title: 'Core Graphic Design Principles: Contrast, Alignment & Repetition', notes: 'C.A.R.P. principles applied to digital banners, posters and web cards', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-2-2', chapterNumber: 2, title: 'Color Theory in Practice: Harmonies, Psychology & Palette Generators', notes: 'Monochromatic, complementary, triadic palettes; warm vs cool tones', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-2-3', chapterNumber: 3, title: 'Typography Fundamentals: Font Classification, Pairing & Kerning', notes: 'Serif vs Sans-serif, script pairing rules, line spacing (leading) & letter spacing', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-2-4', chapterNumber: 4, title: 'Mastering White Space & Visual Hierarchy for Eye Movement', notes: 'F-pattern, Z-pattern reading flows, focal point placement and uncrowded layouts', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-3',
        code: 'MOD-3',
        name: 'Elements, Frames & Vector Assets',
        description: 'Shapes, photo frames, grids, vector illustrations & custom asset search keywords',
        chapters: [
          { id: 'canva-3-1', chapterNumber: 1, title: 'Working with Shapes, Lines, Gradients & Vector Graphics', notes: 'Customizing vector colors, border styling, drop shadows and gradient fills', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-3-2', chapterNumber: 2, title: 'Photo Frames & Grids: Creating Magazine Layouts & Collages', notes: 'Multi-photo grids, clipping masks with custom letter/number frames', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-3-3', chapterNumber: 3, title: 'Secret Search Keywords for Hidden Elements, 3D Assets & Stickers', notes: 'Curated keyword lists (set:nAF..., organic doodle, clay 3d, paper tear)', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-3-4', chapterNumber: 4, title: 'Layer Management: Forward, Backward, Locking & Group Alignments', notes: 'Position panel, tidy up tool, distribute evenly, alignment guides', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-4',
        code: 'MOD-4',
        name: 'Photo Editing & Image Manipulation',
        description: 'Background removal, Magic Eraser, filters, lighting adjustments & image enhancement',
        chapters: [
          { id: 'canva-4-1', chapterNumber: 1, title: 'Background Remover (BG Remover) & Precision Cutouts', notes: 'Erase & restore brush, cleaning edges, hair and transparent objects', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-4-2', chapterNumber: 2, title: 'Magic Eraser & Object Removal for Clean Photography', notes: 'Removing photobombers, wires, unwanted objects and blemishes seamlessly', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-4-3', chapterNumber: 3, title: 'Photo Enhancements: Brightness, Contrast, Saturation, Tint & Vignette', notes: 'Professional color grading, warm sunsets, moody dark aesthetics, clarity', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-4-4', chapterNumber: 4, title: 'Drop Shadows, Glowing Outlines & Duotone Filter Effects', notes: 'Page curl shadow, floating drop shadow, neon YouTube thumbnail outline effect', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-5',
        code: 'MOD-5',
        name: 'Typography, Text Effects & Styles',
        description: 'Curved text, neon effects, hollow outlines, glitch and brand typography kits',
        chapters: [
          { id: 'canva-5-1', chapterNumber: 1, title: 'Curved & Circular Text Effects for Badges and Logos', notes: 'Adjusting curve angle, circular stamping and emblem typography', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-5-2', chapterNumber: 2, title: 'Neon, Glitch, Hollow, Splice & Shadow Text Styling', notes: 'Creating retro neon signs, cyberpunk glitch typography and layered 3D text', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-5-3', chapterNumber: 3, title: 'Gradient Text & Masking Images Inside Typography', notes: 'Photo letter frames, gradient text fills using element clipping hacks', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-5-4', chapterNumber: 4, title: 'Bullet Points, Numbered Lists & Paragraph Formatting', notes: 'Clean leading, hanging indents, columns and professional text hierarchy', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-6',
        code: 'MOD-6',
        name: 'Social Media Design & Carousels',
        description: 'Instagram posts, seamless carousels, YouTube thumbnails, Stories & Reel covers',
        chapters: [
          { id: 'canva-6-1', chapterNumber: 1, title: 'Designing High-CTR YouTube Thumbnails that Stand Out', notes: 'Expressive cutouts, bold high-contrast text, 3-element thumbnail formula', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-6-2', chapterNumber: 2, title: 'Seamless Instagram Multi-Slide Carousels (Split Grid Technique)', notes: 'Continuous image panning across slides, hook slide, value slides & CTA slide', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-6-3', chapterNumber: 3, title: 'Instagram Stories, Poll Stickers & Reel Cover Designs', notes: 'Safe zones for Instagram UI, aesthetic vertical templates, cohesive grid covers', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-6-4', chapterNumber: 4, title: 'Facebook Banners, LinkedIn Headers & Twitter/X Header Graphics', notes: 'Device responsive safe margins, brand tagline, professional profile synergy', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-7',
        code: 'MOD-7',
        name: 'Branding Kits & Marketing Collateral',
        description: 'Brand identity kits, logos, business cards, flyers, brochures & pitch decks',
        chapters: [
          { id: 'canva-7-1', chapterNumber: 1, title: 'Setting Up a Professional Brand Kit: Logos, Palettes & Fonts', notes: 'Brand assets centralization, one-click brand style application across projects', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-7-2', chapterNumber: 2, title: 'Logo Design: Minimalist Wordmarks, Monograms & Emblem Logos', notes: 'Vector logo rules, transparent PNG exports, SVG vector format', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-7-3', chapterNumber: 3, title: 'Modern Business Cards, Letterheads & Digital Invoices', notes: 'Standard 3.5x2 inch print card, QR code generation, click-to-email links', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-7-4', chapterNumber: 4, title: 'Marketing Flyers, Tri-Fold Brochures & Promotional Posters', notes: 'Fold guidelines, print margins, promotional event flyer layouts & hierarchy', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-8',
        code: 'MOD-8',
        name: 'Documents, Presentations & Print Ready Media',
        description: 'Pitch decks, executive resumes, multi-page PDFs, print bleed & CMYK exports',
        chapters: [
          { id: 'canva-8-1', chapterNumber: 1, title: 'Interactive Slide Presentations & Corporate Pitch Decks', notes: '16:9 widescreen layout, slide transitions, charts, data visualizers & Presenter view', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-8-2', chapterNumber: 2, title: 'Modern ATS-Friendly Resumes & Creative Visual Portfolios', notes: 'Clean single/double column layout, skill ratings, contact icons & PDF hyperlinks', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-8-3', chapterNumber: 3, title: 'Multi-Page eBooks, Workbooks & Interactive PDF Forms', notes: 'Page numbering, table of contents, clickable links & digital workbook fields', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-8-4', chapterNumber: 4, title: 'Print Readiness: Bleed, Safe Zones, CMYK vs RGB & High-Res PDF Export', notes: 'PDF Print format, crop marks, color profile conversion & commercial print check', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-9',
        code: 'MOD-9',
        name: 'Video Editing, Motion Graphics & Animation',
        description: 'Timeline editor, page/element transitions, background music, MP4 & animated GIFs',
        chapters: [
          { id: 'canva-9-1', chapterNumber: 1, title: 'Canva Video Timeline: Trimming, Splitting & Layering Clips', notes: 'Multi-track timeline, syncing clips, aspect ratio conversion (9:16 to 16:9)', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-9-2', chapterNumber: 2, title: 'Element Animations: Pan, Fade, Pop, Wipe, Baseline & Kinetic Type', notes: 'In-animation, out-animation, speed controls and motion effects', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-9-3', chapterNumber: 3, title: 'Page Transitions & Audio Synchronization (BGM, Sound Effects)', notes: 'Dissolve, slide, match & move transition; audio fade in/fade out & beat sync', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-9-4', chapterNumber: 4, title: 'Exporting Animated GIFs, MP4 High Definition & Transparent Stickers', notes: 'Render settings, compression, looping GIF animations for web & social media', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-10',
        code: 'MOD-10',
        name: 'Canva AI & Magic Studio Workflows',
        description: 'Magic Write, Magic Design, Magic Edit, Magic Media (Text-to-Image) & Bulk Creation',
        chapters: [
          { id: 'canva-10-1', chapterNumber: 1, title: 'Magic Media: Generating Custom AI Images & Graphics from Prompts', notes: 'Prompt engineering inside Canva, selecting art styles (Photographic, 3D, Anime)', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-10-2', chapterNumber: 2, title: 'Magic Edit & Magic Expand: Transforming & Extending Photo Backgrounds', notes: 'Brush-selecting areas and replacing clothing, objects or backgrounds with AI', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-10-3', chapterNumber: 3, title: 'Magic Write & AI Copywriting for Social Captions & Headings', notes: 'Tone of voice adjustments, rewriting, summarizing text and headline ideation', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-10-4', chapterNumber: 4, title: 'Bulk Create: Automating 50+ Social Media Posts with CSV / Google Sheets', notes: 'Connecting tabular data to design templates, generating bulk quotes and certificates', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
      {
        id: 'canva-mod-11',
        code: 'MOD-11',
        name: 'Client Projects & Portfolio Building',
        description: 'Client briefs, product mockups, exporting presentations & building a design portfolio',
        chapters: [
          { id: 'canva-11-1', chapterNumber: 1, title: 'Smartmockups: Creating 3D Device, T-Shirt, Book & Package Mockups', notes: 'Applying designs to realistic 3D laptops, smartphones, mugs and apparel', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-11-2', chapterNumber: 2, title: 'Interpreting Client Briefs & Rapid Prototyping in Canva', notes: 'Moodboards, style discovery, handling client feedback revisions gracefully', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-11-3', chapterNumber: 3, title: 'Sharing Designs: View-only Links, Editable Templates & Client Hand-off', notes: 'Creating shareable Canva template links without compromising originals', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
          { id: 'canva-11-4', chapterNumber: 4, title: 'Building a Polished Canva Design Portfolio & Freelance Case Studies', notes: 'Assembling case studies, before/after showcases and Tutedude course capstone project', readingNotes: false, deepStudy: false, revision: false, isFinished: false },
        ],
      },
    ],
  },
];

// Clean slate: Ensure absolutely 0 progress across every single task and chapter in all programs
export const INITIAL_PROGRAM_TABS: ProgramTab[] = RAW_PROGRAM_TABS.map((program) => ({
  ...program,
  siTasks: program.siTasks?.map((t) => ({
    ...t,
    currentCount: 0,
    status: 'pending' as const,
    finishedAt: undefined,
  })),
  subjects: program.subjects?.map((s) => ({
    ...s,
    chapters: s.chapters.map((c) => ({
      ...c,
      readingNotes: false,
      deepStudy: false,
      revision: false,
      isFinished: false,
      finishedAt: undefined,
    })),
  })),
}));
